### ISSUE TITLE
Layer overlaping other layers

### ISSUE THREAD

**Issue by miszokienka** [uprel/gisapp#79] opened 2018-06-11 19:32 UTC
If you turn on a layer that is lower in layers tree than it overlaps all the layers that were loaded before. For viewing all the layers that should be upper of the layer that was turned on you need to turn them off and on again.
I'm not 100% sure but it can be a latest version bug because I don't remember if it happened in the past.

**Comment by uprel** [comment] 2018-06-14 12:05
Confirmed. This is bug since this commit 0f58eb09303a6f0e7b2373bc1b8dbde84d2e8543 and then since version 1.7.0. Fix coming soon. When switching layers on/off  it is not respecting layer order.

**Comment by uprel** [comment] 2018-06-16 06:01
Fixed in release 1.7.4

**Closed by uprel** 2018-06-16 06:01 UTC
Labels: bug
